name: deploy

on:
  push:
    branches:
      - never/trigggggggggerd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
      - run: npm install
      - run: npm run build-prd
